version: '3'
services:
  springbootapp:
    image: immortalkrazy/springapp:latest
    container_name: springboot
    ports:
      - 8080:8080
    depends_on:
      - mongo
    restart: on-failure
  mongo:
    image: lerndevops/mongo
    container_name: springboot-mongo
    ports:
      - 27017:27017
    volumes:
      - /home/compose/data:/root/edureka/springApp/data/db
      - /home/compose/data-bkp:/root/edureka/springApp/data/bkp
    restart: always
